const data = [
  {
    id: 'A5-Pro-CC',
    name: 'A5 Pro CC',
    height: 153.58,
    width: 76.38,
    thickness: 8.75,
    weight: 164,
    screen: 5.84,
    image: '/A5-Pro-CC.jpg',
    type: 'mobile',
    cpu: ['UNISOC Tiger T610'],
    ram: ['4GB', '6GB'],
    storage: ['64GB', '128GB'],
    battery: '4000mAh',
    camera: ['1300万画素'],
    biometrics: ['指紋'],
    ipCode: [''],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Hisence', 'Android', 'E-inc'],
    content: '# AQUOS sense4\n\n## 発売日時\n\n- 2020 年 6 月 10 日\n\n## 特徴\n\n### 長所\n\n- 世界初のカラー電子ペーパー搭載スマートフォンなので、液晶や有機 EL 搭載のものと比べると目が疲れにくい\n- 旭化成製の AK4377 という DAC を搭載していて音が良い\n\n### 短所\n\n- 電子ペーパーなので4096色しか表示できない上に更新に時間がかかるため、動画のようなコンテンツには不向きである\n- 中国向け端末なので、日本の技適を取得していない\n- GMS (Google Mobile Service) がインストールされていないため、 Google Play ストアが利用できない\n',
  },
  {
    id: 'AQUOS-sense4',
    name: 'AQUOS sense4',
    height: 148,
    width: 71,
    thickness: 8.9,
    weight: 177,
    screen: 5.8,
    image: '/AQUOS-sense4.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 720G'],
    ram: ['4GB'],
    storage: ['64GB'],
    battery: '4570mAh',
    camera: ['広角: 800万画素', '望遠: 800万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: ['IPX8'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Sharp', 'Android', 'AQUOS'],
    content: '# AQUOS sense4\n\n## 発売日時\n\n2020年11月6日\n  \n## 特徴\n\n### 長所\n\n- バッテリーが優秀で長持ちする\n- サイズが小型で軽量\n\n### 短所\n\n- カメラ性能が普通\n\n## 大容量バッテリー\n\nシャープ独自の圧倒的な省電力を誇る新IGZOディスプレイと、大容量の4,570mAhバッテリーの搭載で、1週間電池残量を気にせず使用可能。また、省電力かつ、大容量でありながら、使いやすい端末の大きさをキープしている。\n\n## 高性能CPU\n\nSnapdragon 720G を搭載。AQUOS sense3と比べて処理性能が約2.2倍向上。また、ストレージにUFS規格を採用することで、データの読込速度も約2.4倍向上し、アプリのすばやい起動やストレスフリーの使い心地で快適に使用できる。\n',
  },
  {
    id: 'AQUOS-zero5G-basic',
    name: 'AQUOS zero5G basic',
    height: 161,
    width: 75,
    thickness: 9.0,
    weight: 182,
    screen: 6.4,
    image: '/AQUOS-zero5G-basic.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 765'],
    ram: ['8GB'],
    storage: ['128GB'],
    battery: '4050mAh',
    camera: ['広角: 1310万画素', '望遠: 800万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: ['IP5X'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Sharp', 'Android', 'AQUOS'],
    content: '# AQUOS zero5G basic\n\n## 発売日時\n\n2020年10月9日\n  \n## 特徴\n\n### 長所\n\n- イヤホンジャック搭載や指紋認証など使いやすい\n- バッテリーが優秀\n\n### 短所\n\n- 重量が 182g と重め\n\n## 高性能ディスプレイ\n\n4倍速240Hz駆動でなめらかな描画。さらに指に機敏に反応し想像を超えるタッチ体験可能な高速240Hzタッチレスポンスによって操作性能向上。\n\n## DisplayPort対応\n\nスマホを大画面モニターにつなぐことでVR・AR機器などに接続しさらに映像やゲームを楽しめる。\n',
  },
  {
    id: 'Galaxy-S20',
    name: 'Galaxy S20',
    height: 158,
    width: 74,
    thickness: 7.8,
    weight: 163,
    screen: 6.7,
    image: '/Galaxy-S20.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 865'],
    ram: ['12GB'],
    storage: ['128GB'],
    battery: '4000mAh',
    camera: ['広角: 1200万画素', '望遠: 6400万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: ['IP68'],
    gpu: [],
    hasEarphone: false,
    charge: 'Type-C',
    tags: ['Samsung', 'Android', 'Galaxy'],
    content: '# Galaxy S20\n\n## 発売日時\n\n2020年2月11日\n  \n## 特徴\n\n### 長所\n\n- 画面が比較的大きい\n- トリプルカメラ搭載\n\n### 短所\n\n- 重く、少し持ちづらい\n- 価格が高め\n\n## 高性能カメラ搭載\n\nGalaxy S20の高解像度カメラは、64MPと通常のカメラの５倍以上の精密さで写真を撮影できる。鮮明度が変わらない、より鮮やかな高解像度を実現できる。\n\n## 8Kビデオスナップ\n\n8Kビデオスナップで最高解像度のビデオを撮影できる。シチュエーションに合わせてHDから撮影可能。容量の大きい、8Kビデオを後から自由に解像度変更できる。これはUHDの4倍、FHD（フルHD）の16倍。さらに手振れ補正で安定した撮影を可能に。\n',
  },
  {
    id: 'Google-Pixel-5',
    name: 'Google Pixel 5',
    height: 144.7,
    width: 70.4,
    thickness: 8.0,
    weight: 151,
    screen: 6.0,
    image: '/Google-Pixel-5.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 765G'],
    ram: ['8GB'],
    storage: ['128GB'],
    battery: '4080mAh',
    camera: ['広角: 1220万画素', '超広角: 1600万画素'],
    biometrics: ['指紋'],
    ipCode: ['IP5X'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Google', 'Android', 'Google Pixel'],
    content: '# Google Pixel 5\n\n## 発売日時\n\n2020年10月15日\n  \n## 特徴\n\n### 長所\n\n- Google サービスとの連携に強い\n- 大きさがコンパクト\n\n### 短所\n\n- GooglePixel4と比べcpuなどのスペックが少し低め\n\n## ウルトラワイドレンズ搭載\n\nウルトラワイドレンズによって大迫力かつ美しい写真を撮影できる。また、他にも影が写真に入り込んでもライトで被写体の光量を補うことで様々な写真を撮れる。\n\n## 長時間バッテリー\n\n自動調整バッテリーによって、よく使うアプリを認識して優先的にバッテリーを供給し、使用率の低いアプリへのバッテリーを減らして電池を長持ちさせる。最大48時間駆動可能な大容量バッテリー\n',
  },
  {
    id: 'HP-Spectre',
    name: 'Spectre x360 14',
    height: 220,
    width: 298,
    thickness: 17,
    weight: 1360,
    screen: 13.5,
    image: '/HP-spectre.jpg',
    type: 'pc',
    cpu: ['Core i5-1135G7', 'Core i7-1165G7'],
    ram: ['8GB', '16GB'],
    storage: ['256GB', 'SSD: 512GB + 32GB Optaneメモリー', 'SSD: 1TB + 32GB Optaneメモリー'],
    battery: '',
    camera: ['92万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: [''],
    gpu: ['Intel Iris Xe Graphics'],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['HP', 'Windows10', 'laptop', '2in1'],
    content: '# Spectre x360 14\n\n## 発売日時\n\n- 2020 年 12 月\n\n## 特徴\n\n### 長所\n\n- ヒンジが 360° 回転するため様々な使い方ができる\n- 3:2 の画面比を採用しているため、他端末に比べ縦に広く情報が表示できる\n\n### 短所\n\n- 2in1 PC にしては比較的重い\n\n## PC-スマホ間のファイル共有が簡単に\n\n専用のアプリを使って、スマートフォンとパソコン間のデータ転送を双方向にできる。加工した写真や動画を簡単な設定で共有できる。\n\n## 強力なバッテリー\n\n最大 15 時間バッテリーがもち、充電も 45 分で**7**時間も駆動可能\n\n## プライバシー\n\nキーボードのキーを押すだけでカメラをオン/オフを切り替え可能  \nLED キー付きの専用ミュートマイクでマイクのオン/オフを切り替え可能  \nHP Sure View Reflect という反射型プライバシースクリーンを内蔵しているので覗き見される心配がない\n',
  },
  {
    id: 'HUAWEI-P30-lite',
    name: 'HUAWEI P30 lite',
    height: 153,
    width: 73,
    thickness: 7.4,
    weight: 159,
    screen: 6.1,
    image: '/P30-Lite.jpg',
    type: 'mobile',
    cpu: ['Kirin 710'],
    ram: ['4GB'],
    storage: ['128GB'],
    battery: '3340mAh',
    camera: ['広角: 2400万画素', '望遠: 800万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: ['IP5X'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['HUAWEI', 'Android'],
    content: '# Galaxy S20\n\n## 発売日時\n\n2019年8月8日\n  \n## 特徴\n\n### 長所\n\n- 非常に安価\n- 被写界深度レンズという特殊なレンズがありるため、自然なボケ感のある写真が撮影できる\n\n### 短所\n\n- 発売が2019年のため古い機種\n  \n## 120度超広角カメラ搭載\n\n画角120度の超広角カメラで迫力のある広大な風景を撮影可能。さらに、アウトカメラ22種類、インカメラ8種類、計30種類ものカメラシスタントで適切な色、明るさなどを調整できる。\n\n## 3D湾曲デザイン\n\n他のスマホとは違う端末の背面を少しだけ湾曲させることで握りやすく手のひらに快適にフィットする。重さや端末の大きさも平均的で日常的な使用感は抜群でストレスフリーな端末。\n',
  },
  {
    id: 'MacBook-Pro',
    name: 'MacBook Pro',
    height: 212.4,
    width: 304.1,
    thickness: 15.6,
    weight: 1400,
    screen: 13.3,
    image: '/MacBook-Pro.jpg',
    type: 'pc',
    cpu: ['Apple M1'],
    ram: ['8GB ユニファイドメモリ', '16GB ユニファイドメモリ'],
    storage: ['256GB SSD / 512GB SSD', '1TB SSD / 2TB SSD'],
    battery: '',
    camera: ['720p FaceTime HDカメラ'],
    biometrics: ['指紋'],
    ipCode: [''],
    gpu: ['Apple M1'],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['macOS', 'Apple', 'Latest', 'laptop'],
    content: '# MacBook Pro\n\n## 発売日時\n\n- 2020 年 11 月\n\n## 特徴\n\n### 長所\n\n- Apple が新規開発した SoC を搭載しているため、省電力性に優れている上にほとんどのラップトップ向け CPU より高速に動作する。\n- 電源効率が非常によく、2018年の MacBook Pro 15インチだと3時間未満で100%から0%になってしまうような作業をずっと続けていても実測で10時間以上持つ。\n\n### 短所\n\n- USB Type-C のポートを2つしか搭載していないため、メインマシンとして運用するためには拡張性が乏しい。\n- 設計上、公式では画面が2枚（内臓1枚 + 外付け1枚）以下の構成でしか使用できない。\n\n## Apple Silicon\n\nApple Silicon という Apple 独自設計の ARMアーキテクチャ SoC （**S**ystem **o**n a **C**hip: 複数のパーツを搭載したプロセッサ）を採用することにより、電源効率の向上と性能の飛躍的向上に貢献している。  \n  \nその一方、従来のデファクトスタンダードであった AMD64 （x86_64）のシステムと設計上の互換がないため、 ARM64 ネイティブでの動作に対応していないアプリケーションは Rosetta 2 という公式の変換プログラムが翻訳した後に実行することになるが、変換しても正常に動作しないアプリがあるため、現時点での購入・使用は若干の人柱的要素を含んでいる。  \n  \nなお、 Microsoft Office や一般的なモダンブラウザ等のオフィス用途のアプリケーションは既にネイティブ対応版がリリースされているため、レポートを書く・営業先に持っていき資料を提示する・経理作業を行う等の目的には最適なマシンだと言える。\n\n## macOS\n\nWindows と Surface シリーズ、 Android と Pixel シリーズのように「 OS を作っているメーカーがハードも作った」という構造ではなく、「もとからハードとソフトが限定された組み合わせで使われる」という前提のもと開発されているため、ハードウェアとソフトウェアの相性問題が限りなく少ない。  \n  \nまた、 macOS は UNIX をベースとした OS であるため、その後発である Linux というサーバ用途として広く普及しているフィンランド出身の天才リーナス・トーバルズによって開発された OS と似たような操作感であることが好まれ、主に Web 系やモバイル系のエンジニアから好まれている。  \n',
  },
  {
    id: 'ROG-Phone-3',
    name: 'ROG Phone 3',
    height: 171,
    width: 78,
    thickness: 7.9,
    weight: 240,
    screen: 6.6,
    image: '/ROG-Phone.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 865 Plus'],
    ram: ['12GB', '16GB'],
    storage: ['512GB'],
    battery: '6000mAh',
    camera: ['広角: 1200万画素', '望遠: 6400万画素'],
    biometrics: ['指紋'],
    ipCode: ['IP5X'],
    gpu: [],
    hasEarphone: false,
    charge: 'Type-C',
    tags: ['ASUS', 'Android', 'Rog'],
    content: '# Rog Phone3\n\n## 発売日時\n\n2020年9月26日\n  \n## 特徴\n\n### 長所\n\n- ゲーミングスマートフォン\n- 60000mAh もの大容量バッテリー\n\n### 短所\n\n- 非常に高価\n- サイズが大きく重い\n\n## ゲーミングスマホの最高峰\n\n5G対応の最新のSnapdragon 865 Plusを搭載。他を圧倒する144Hz/1ms対応の超高速ディスプレイを搭載。従来のROG Phoneよりもさらに使い勝手を向上した超音波タッチセンサーAirTrigger　3をはじめ、使いやすい側面充電ポート、デュアルフロントスピーカーなどよりゲームへの没入を深く楽しめる。\n\n## 超大容量バッテリー\n\n最新のゲームはバッテリーを多く消費するがこの端末は6,000mAhの超大容量バッテリーを搭載しており、ゲームを長時間連続して楽しむことができる。また、複数のカスタムバッテリーモードや独自の休止機能など、多数の省電力メカニズムを搭載することで、バッテリー駆動時間を飛躍的に向上。\n',
  },
  {
    id: 'Razer-Blade-Stealth',
    name: 'Razer Blade Stealth',
    height: 210,
    width: 304.6,
    thickness: 15.3,
    weight: 1410,
    screen: 13.3,
    image: '/Razer-Blade-Stealth.jpg',
    type: 'pc',
    cpu: ['Core i7-1165G7'],
    ram: ['16GB'],
    storage: ['512GB'],
    battery: '',
    camera: ['HD 720p Windows Hello 準拠赤外線カメラ'],
    biometrics: ['顔'],
    ipCode: [''],
    gpu: ['NVIDIA GeForce GTX 1650 Ti Max Q Design 4GB GDDR6 VRAM'],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Razer', 'Windows10', 'laptop', 'Gaming'],
    content: '# ThinkPad X13 Gen1\n\n## 発売日時\n\n- 2020 年 6 月\n\n## 特徴\n\n### 長所\n\n- GPU を搭載しているため、他のマシンと比べると動画編集や 3D モデリングなどという重い作業をスムーズに行うことができる。\n- キーボードが RAZER CHROMA 対応であり、1680万色のカラーオプションと効果のコレクションにより、ライティングをパーソナライズできる。\n\n### 短所\n\n- かなり高額である上に、 GPU が微妙なグレードである。\n\n## Razer 製デバイス\n\nPC ゲームに触れたことのある人なら一度は聞いたことのあるメーカーが製造しているマシンであるため、ゲーマーにターゲティングしたような外装・機能・性能となっている。  \n  \n一般に、同じようなスペックのマシンは画面サイズが15インチ以上であったり、厚み重みが桁違いであり、お世辞にも持ち運びには適しているとは言い難い状況であったが、その状況下で持ち運べるという点に拘ったマシンとしてはかなりの完成度である。\n\n## 冷却性能\n\nウルトラブックの部類ではあるものの、ゲーミングマシンであることには変わりがないので、冷却性能は一般のウルトラブックよりも優れている。  \n  \n[ASCII でのテスト結果](https://ascii.jp/elem/000/004/033/4033262/)によると、同じ CPU を搭載し、かなりチューニングされていることで有名な Dell 製の [XPS13](/device/XPS-13) と比較しても1割ほど高速に動作する。\n\nまた，同テスト結果より、内臓されている Intel Iris Xe グラフィックスも最大で2割近く高速に動作する。\n',
  },
  {
    id: 'ThinkPad-X13-Gen1',
    name: 'ThinkPad X13 Gen1',
    height: 217,
    width: 311.9,
    thickness: 16.5,
    weight: 1180,
    screen: 13.3,
    image: '/ThinkPad-X13-Gen1.jpg',
    type: 'pc',
    cpu: ['Core i3-10110U', 'Core i5-10210U', 'Core i7-10510U'],
    ram: ['8GB', '16GB', '32GB'],
    storage: ['128GB / 256GB / 512GB', '1TB / 2TB'],
    battery: '',
    camera: ['720p HD カメラ'],
    biometrics: ['指紋', '顔'],
    ipCode: [''],
    gpu: ['インテル® UHD グラフィックス'],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Lenovo', 'Windows10', 'laptop', 'ThinkPad'],
    content: '# ThinkPad X13 Gen1\n\n## 発売日時\n\n- 2020 年 5 月\n\n## 特徴\n\n### 長所\n\n- 12インチのサイズに13インチの液晶を搭載しているため、省スペース性に優れる\n- 品薄ではあるが、 AMD Ryzen シリーズを搭載したモデルも用意されているため、柔軟なスペックから選ぶことが可能である。\n\n### 短所\n\n- 他のマシンと比べると厚みがあるため、薄さを求める人には不向きである。\n\n## カスタマイズ性・拡張性に優れている\n\n購入時の豊富なカスタマイズのラインナップに加え、購入後に SSD を交換することができ、容量が足りないといった問題に対峙した場合にサポートの手を借りずに問題解決することが可能である。  \n  \nまた、日常的に使う USB Type-A ポートやビジネスシーンなどに於ける大画面での資料提示等にも対応できるような HDMI ポート、部活や仕事での遠征や出張で泊まったホテルにイーサネットケーブルしかない場合にも接続できるようなイーサネット拡張ケーブルが付属しているため、追加でハブなどを買わなくてもよく、荷物も少なくて済む。\n\n## 情報が豊富\n\nThinkPad はキーボードにこだわり製造されているため、長時間タイピングをする必要があるエンジニアに絶大な人気を誇っている。  \n  \nまた、ビジネスリース落ちである数世代前の中古マシンが2~3万で大量に放出されるため、格安でそこそこ新しいマシンが手に入るとのことで金銭的余裕のない学生エンジニアの間でも他とは一線を画する人気を誇っている。  \n\nそのため、 Linux というサーバ用途として広く普及しているフィンランド出身の天才リーナス・トーバルズによって開発された OS の情報も豊富であり、他のマシンと比較してトラブルシューティングが容易であるという利点がある。\n\n## キーボード・トラックポイント\n\n前項でも述べたように、 ThinkPad はキーボードにこだわり製造されているため、キーボード単体で発売されるほどの人気を博している。  \n  \nまた、それ以上にトラックポイントという小さく赤いマウスの代替となるポインティングデバイスにも熱狂的なファンが存在するほど、慣れると離れられなくなる。\n',
  },
  {
    id: 'XPS-13',
    name: 'XPS 13 (2020)',
    height: 198.70,
    width: 295.70,
    thickness: 14.80,
    weight: 1250,
    screen: 13.4,
    image: '/XPS-13.jpg',
    type: 'pc',
    cpu: ['Core i3-1115G4', 'Core i5-1135G7', 'Core i7-1165G7'],
    ram: ['16GB', '32GB'],
    storage: ['SSD: 512GB', 'SSD: 1TB'],
    battery: '',
    camera: ['92万画素'],
    biometrics: ['指紋', '顔'],
    ipCode: [''],
    gpu: ['Intel UHD Graphics', 'Intel Iris Xe Graphics'],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['DELL', 'Windows10', 'laptop'],
    content: '# XPS 13 (2020)\n\n## 発売日時\n\n- 2020 年 10 月\n\n## 特徴\n\n### 長所\n\n- 16:10 の比率の画面を採用しているため、画面を通常よりも大きく使える\n- 13 インチの液晶を搭載しているが、横幅が 30cm を切っている\n\n### 短所\n\n- USB-typeA のポートを搭載していないため、一般的な USB に対応した製品を使用するときは、USB のハブやドックが必要になる\n- 高価\n\n## 従来のモデルとの比較\n\n画面比が 16:9 から 16:10 となったため、画面は 6.8%大きくなった。また、タッチパッドは 17%も大きくなったため、より操作がしやすくなった。\n\n## 強力なプロセッサ\n\nインテル Evo プラットフォームを採用することで、バッテリー持続時間は長く、高いパフォーマンスを実現している。  \nまた、Intel Iris Xe グラフィックスを搭載していて、以前は重くて動作できなかった PC ゲームや、動画編集も快適にこなせる製品となっている。\n',
  },
  {
    id: 'Xperia-10-2',
    name: 'Xperia 10 Ⅱ',
    height: 151,
    width: 67.3,
    thickness: 7.3,
    weight: 151,
    screen: 4.7,
    image: '/Xperia-10-2.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 665'],
    ram: ['4GB'],
    storage: ['64GB'],
    battery: '3600mAh',
    camera: ['広角: 800万画素', '望遠: 800万画素'],
    biometrics: ['指紋'],
    ipCode: ['IPX5', 'IPX8', 'IP6X'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Sony', 'Android', 'Xperia'],
    content: '# Xperia 10 Ⅱ\n\n## 発売日時\n\n2020年5月29日\n  \n## 特徴\n\n### 長所\n\n- 軽量でコンパクト\n- マルチウインドウを使いやすい\n\n### 短所\n\n- カメラ性能はそこそこ\n- サイズが縦長のため慣れが必要\n\n## 21:9の大画面ディスプレイ\n\n映画とほぼ同じ比率、21:9の有機ELディスプレイで迫力の映像を大画面で。ブラビアで培った画作りのノウハウにより、豊かで自然な色合いや、繊細な色の違いも表現できる。また、マルチウインドウで上下で2つのアプリを同時操作でき、作業の効率を上げることができる。\n\n## 軽量ボディ\n\n約151gの軽くて持ちやすいスリムボディに、先進の機能を凝縮。\nミッドレンジXperia初となる有機ELディスプレイ、トリプルレンズカメラを搭載し、\n動画視聴や写真撮影など、日常生活を上質なものに。\n',
  },
  {
    id: 'Xperia-5-2',
    name: 'Xperia5 Ⅱ',
    height: 158,
    width: 68,
    thickness: 9.1,
    weight: 163,
    screen: 6.1,
    image: '/Xperia-5-2.jpg',
    type: 'mobile',
    cpu: ['Snapdragon 865'],
    ram: ['8GB'],
    storage: ['128GB'],
    battery: '4000mAh',
    camera: ['広角: 1220万画素', '望遠: 1220万画素'],
    biometrics: ['指紋'],
    ipCode: ['IP5X', 'IPX8', 'IP6X'],
    gpu: [],
    hasEarphone: true,
    charge: 'Type-C',
    tags: ['Sony', 'Android', 'Xperia'],
    content: '# Xperia5 Ⅱ\n\n## 発売日時\n\n2020年10月17日\n  \n## 特徴\n\n### 長所\n\n- 軽量でコンパクト\n- マルチウインドウを使いやすい\n\n### 短所\n\n- カメラ性能はそこそこ\n- サイズが縦長のため慣れが必要\n\n## 高音質なAUDIO\n\nDSEE Ultimateによってストリーミングサービスで聴く最新曲も、ハイレゾ相当の高音質に。\nまた、Dolby ATMOSで臨場感のある立体サウンドを再生できる。\n\n## スマホの域を超えたゲーム体験\n\nすばやい動きもなめらかに映す120Hz駆動ディスプレイに加え、240Hzの残像低減技術により、さらにくっきりした映像に。最大240Hzの高速タッチ検出が可能になり、複雑な指の動きにもしっかり反応。\n視野が広く、ゲームに有利な21：9の大画面でプレイ可能。\n',
  },
  {
    id: 'iPhone-11',
    name: 'iPhone 11',
    height: 150.9,
    width: 75.7,
    thickness: 8.3,
    weight: 194,
    screen: 6.1,
    image: '/iPhone-11.jpg',
    type: 'mobile',
    cpu: ['A13 Bionic'],
    ram: ['不明'],
    storage: ['64GB', '128GB', '256GB'],
    battery: '3110mAh',
    camera: ['広角: 1200万画素', '超広角: 1200万画素'],
    biometrics: ['顔'],
    ipCode: ['IP68'],
    gpu: [],
    hasEarphone: false,
    charge: 'Lightning',
    tags: ['Apple', 'iOS', 'iPhone'],
    content: '# iPhone 11\n\n## 発売日時\n\n2019年9月20日\n  \n## 特徴\n\n### 長所\n\n- 画面が比較的大きい\n- トリプルカメラ搭載\n\n### 短所\n\n- 重く、少し持ちづらい\n- 指紋認証がなくなった\n\n## iPhoneXとの比較\n\niPhoneXシリーズと比べカメラ性能が大きく向上した。超広角レンズが搭載されインカメラの画素数も700万画素から1200万画素へと変わった。大きさや重量はほぼ変わっていないがその他の部分で小型化が図られている。\n\n## ディスプレイの強度\n\niPhoneシリーズはXからディスプレイが液晶パネルから有機ELになったことで傷がつきやすくなったが11では強度が大幅に上がっていることで壊れにくくなった。ディスプレイの強度はあまり着目しない人もいるが端末を選ぶ基準の一つにはなる。\n',
  },
  {
    id: 'iPhone-12',
    name: 'iPhone 12',
    height: 146.7,
    width: 71.5,
    thickness: 7.4,
    weight: 162,
    screen: 6.1,
    image: '/iPhone-12.jpg',
    type: 'mobile',
    cpu: ['A14 Bionic'],
    ram: ['不明'],
    storage: ['64GB', '128GB', '256GB'],
    battery: '3110mAh',
    camera: ['広角: 1200万画素', '望遠: 1200万画素'],
    biometrics: ['顔'],
    ipCode: ['IP68'],
    gpu: [],
    hasEarphone: false,
    charge: 'Lightning',
    tags: ['Apple', 'iOS', 'iPhone'],
    content: '# iPhone 12\n\n## 発売日時\n\n2020年10月23日\n  \n## 特徴\n\n### 長所\n\n- 11 より小型で高性能\n- カメラ性能の向上\n\n### 短所\n\n- イヤホンジャックがない\n- 指紋認証がない\n\n## iPhone11との比較\n\niPhone11と比較して端末の厚さが11%薄く、サイズが15%小さく、重さが16%軽くなっている。またCPUも進化し5Gをより広いエリアで使用可能になった。\n\n## Super Retina XDRディスプレイ\n\nSuper Retina XDRディスプレイを搭載。LCDではバックライトを使ってすべてのピクセルを同時に照らすが、OLEDでは一つひとつのピクセルが自ら発光する。発光を完全にオフにすれば漆黒になり、輝度を最大1,200ニトに上げればHDRコンテンツを再生できる。また、耐落下性能も4倍に向上している。\n',
  },
  {
    id: 'iPhone-SE',
    name: 'iPhone SE',
    height: 138.4,
    width: 67.3,
    thickness: 7.3,
    weight: 148,
    screen: 4.7,
    image: '/iPhone-SE.jpg',
    type: 'mobile',
    cpu: ['A13 Bionic'],
    ram: ['不明'],
    storage: ['64GB', '128GB', '256GB'],
    battery: '1821mAh',
    camera: ['広角: 1200万画素', '望遠: 1200万画素'],
    biometrics: ['顔'],
    ipCode: ['IP67'],
    gpu: [],
    hasEarphone: false,
    charge: 'Lightning',
    tags: ['Apple', 'iOS', 'iPhone'],
    content: '# iPhone SE\n\n## 発売日時\n\n2020年4月24日\n  \n## 特徴\n\n### 長所\n\n- 小型でコンパクト\n- 非常に安価で高性能\n\n### 短所\n\n- イヤホンジャックがない\n\n## 高性能CPU\n\niPhone SEにはiPhone 11 Proと同じA13Bionicチップを搭載。アプリの起動や最新のゲームのプレイなど、どんな時でも高速かつスムーズに最高の使用感を得ることができる。\n\n## ポートレードモード搭載カメラ\n\n誰かを撮る時でも、セルフィーでも、背景をぼかして被写体を際立たせる。深度コントロールによって背景のぼかしの強弱をシンプルなスライダで調整できる。さらに光と影の調整によって被写体をさらに美しく撮影できる。\n',
  },
]

export default data
